# ワークフロー名
name: housework_bot
on:
  schedule:
    # 定期実行する時間・・・①
    - cron: '0 2 * * *'
    - cron: '30 2 * * *'
    - cron: '45 2 * * *'
    - cron: '0 3 * * *'
    - cron: '0 4 * * *'
    - cron: '0 8 * * *'
    - cron: '0 14 * * *'
  
jobs:
  build:
    # Ubuntuの最新版環境内で処理を実行することを指定
    runs-on: ubuntu-latest

    # 実行する処理＆コマンド指定
    steps:
      - uses: actions/checkout@v2
      - name: Set up Python 3.11.7
        uses: actions/setup-python@v1
        with:
          python-version: 3.11.7
      - name: Install dependencies
        run: |
          # pip更新
          python -m pip install --upgrade pip
          # 必要なパッケージインストール・・・②
          pip install requests
          pip install beautifulsoup4
          pip install pandas
          pip install tqdm
          pip install numpy
          

      - name: Run script
        run: |
          # 定期実行するファイルを指定。・・・③
          python scraping.py
